---
- hosts: ubuntu
  become: true
  tasks:
  ansible_python_interpreter: /usr/bin/python3
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400