---
- hosts: ubuntu
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
    ansible_python_interpreter: /usr/bin/python3
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400